using RedTeam.Extensions.CodeGenerators.Models;

namespace RedTeam.CodeGenerators.Generators.Enumerations;
public static class EnumWriter
{
    public static string GenerateExtensionClass(
        EnumRegistration[] enumRegistrations,
        string assemblyName,
        string methodName, string methodInternal)
    {
        var codeBuilder = new IndentedStringBuilder();
        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();

        codeBuilder
        .AppendLine($"namespace RedTeam.Enums;");





        foreach (var enumRegistration in enumRegistrations)
        {
            WriteMapperClassWithMethods(codeBuilder, enumRegistration);

        }




        codeBuilder.DecrementIndent();

        return codeBuilder.ToString();
    }


    static void WriteMapperClassWithMethods(IndentedStringBuilder codeBuilder, EnumRegistration enumRegistration)
    {
        codeBuilder.AppendLine("/// <summary>")
           .AppendLine($"/// Automapping extensions for {enumRegistration.Name}.")
           .AppendLine("/// </summary>");
        codeBuilder.AppendLine($"public static class {enumRegistration.Name}Mapper")
            .AppendLine("{")
            .IncrementIndent();
        AddToIntMethod(codeBuilder, enumRegistration, enumRegistration.Members);
        AddFromStringMethod(codeBuilder, enumRegistration, enumRegistration.Members);
        codeBuilder.DecrementIndent().AppendLine("}");


    }

    static void AddToIntMethod(IndentedStringBuilder codeBuilder, EnumRegistration enumRegistration, Dictionary<string, int> data)
    {
        codeBuilder.AppendLine("/// <summary>")
         .AppendLine($"///Maps {enumRegistration.Namespace}.{enumRegistration.Name} to an integer.")
         .AppendLine("/// </summary>");
        var toIntMethodDeclaration = $"public static int? ToInt(this global::{enumRegistration.Namespace}.{enumRegistration.Name} value)";
        codeBuilder.AppendLine(toIntMethodDeclaration)
            .AppendLine("{")
            .IncrementIndent();

        codeBuilder.AppendLine("return value switch");
        codeBuilder.AppendLine("{")
            .IncrementIndent();
        var total = enumRegistration.Members.Count();

        foreach (var member in enumRegistration.Members)
        {
            codeBuilder.AppendLine($"global::{enumRegistration.Namespace}.{enumRegistration.Name}.{member.Key} => {member.Value},");
        }
        codeBuilder.AppendLine("_ => null");
        codeBuilder.DecrementIndent().AppendLine("};");

        codeBuilder.DecrementIndent()
            .AppendLine("}");
    }
    static void AddFromStringMethod(IndentedStringBuilder codeBuilder, EnumRegistration enumRegistration, Dictionary<string, int> data)
    {
        codeBuilder.AppendLine("/// <summary>")
      .AppendLine($"///Maps a string to  {enumRegistration.Namespace}.{enumRegistration.Name}.")
      .AppendLine("/// </summary>");
        var fromString = $"public static global::{enumRegistration.Namespace}.{enumRegistration.Name}? FromString(string value)";
        codeBuilder.AppendLine(fromString)
            .AppendLine("{")
            .IncrementIndent();

        codeBuilder.AppendLine("return value?.ToLowerInvariant() switch");
        codeBuilder.AppendLine("{")
                        .IncrementIndent();

        foreach (var member in enumRegistration.Members)
        {

            codeBuilder.AppendLine($"\"{member.Key.ToLowerInvariant()}\" => global::{enumRegistration.Namespace}.{enumRegistration.Name}.{member.Key},");
        }
        codeBuilder.AppendLine("_ => null");
        codeBuilder.DecrementIndent().AppendLine("};");
        codeBuilder.DecrementIndent();
        codeBuilder.AppendLine("}");
    }
}
