using RedTeam.Extensions.CodeGenerators.Models;
using RedTeam.Extensions.Console.CodeGenerators.Models;

namespace RedTeam.Extensions.CodeGenerators;

internal class AddCommandHandlerWriter

{


    public static string GenerateExtensionClass(
        CommandHandlerRegistration[] consumerRegistrations,
        SubCommandHandlerRegistration[] subCommandHandlerRegistrations,
        SubCommandRegistration[] subCommandRegistrations,
        MethodRegistration[] methodRegistrations,
        string assemblyName,
        string methodName, string methodInternal)
    {
        // var configurationType = GetConfigurationType(consumerRegistrations, methodRegistrations);
        var codeBuilder = new IndentedStringBuilder();
        codeBuilder
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("using Cocona;")
            .AppendLine("using Cocona.Builder;")
            .AppendLine("using RedTeam.Extensions.Console;")
            .AppendLine("using Microsoft.Extensions.DependencyInjection;");

        codeBuilder
        .AppendLine($"namespace RedTeam.Extensions.Console;")
        .AppendLine("/// <summary>")
        .AppendLine("/// Extension methods for cocona.")
        .AppendLine("/// </summary>");


        codeBuilder
       .AppendLine("public static class GeneratedAddCommandHandlerConfigurationExtensions")
       .AppendLine("{")
       .IncrementIndent()
       .AppendLine("/// <summary>")
       .AppendLine($"/// Adds  Cocona Commands  from {assemblyName ?? string.Empty}.")
       .AppendLine("/// </summary>")
       .AppendLine("/// <param name=\"builder\">Cocona Builder</param>")

       .AppendLine("/// <returns>cocona app</returns>")
       .Append("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"")
       .Append(ThisAssembly.Product)
       .Append("\", \"")
       .Append(ThisAssembly.InformationalVersion)
       .AppendLine("\")]")
       .Append(string.Equals(methodInternal, "true") ? "internal" : "public")
       .Append(" static global::Cocona.CoconaApp")
       .Append(" Register")
       .Append(methodName ?? "AddCoconaCommandHandlers")
       .AppendLine("(this global::Cocona.Builder.CoconaAppBuilder builder)")
       .AppendLine("{")
       .IncrementIndent();

        //begin registraiton code
        foreach (var consumerRegistration in consumerRegistrations)
        {
            codeBuilder.AppendLine($"builder.Services.AddSingleton<global::RedTeam.Extensions.Console.Commands.ICommand<{consumerRegistration.CommandParametersClassName}>, {consumerRegistration.CommandHandlerClassName}>();");

        }



        //end registration code

        codeBuilder.AppendLine("var app = builder.Build();");
        foreach (var consumerRegistration in consumerRegistrations)
        {

            codeBuilder.AppendLine($"app.AddCommand<{consumerRegistration.CommandParametersClassName}>( \"{consumerRegistration.CommandName}\",  \"{consumerRegistration.CommandDescription}\");");

        }


        if (subCommandHandlerRegistrations.Any())
        {
            var tree = new SubCommandTree(subCommandHandlerRegistrations, subCommandRegistrations);

            tree.GenerateSubCommandCodeRegistrations(codeBuilder);
        }


        foreach (var methodRegistration in methodRegistrations)
        {
            codeBuilder.AppendLine($"{methodRegistration.ClassName}.{methodRegistration.MethodName}(app);");
        }
        codeBuilder
        .AppendLine("return app;")
              .DecrementIndent()
        .AppendLine("}") // method
        .DecrementIndent()
        .AppendLine("}");

        return codeBuilder.ToString();


    }



}
