global using Cocona;
global using Injectio.Attributes;
global using Microsoft.Extensions.DependencyInjection;
global using RedTeam.Extensions.Console;
global using RedTeam.Extensions.Console.Attributes;
global using RedTeam.Extensions.Console.Commands;
global using RedTeam.Extensions.Console.ExtensionMethods;
global using RedTeamGoCli.Commands;
global using RedTeamGoCli.Interfaces;
global using RedTeamGoCli.Models;
global using RedTeamGoCli.Services;
global using Spectre.Console;
global using static RedTeamGoCli.Commands.CommandMetadata;
global using static RedTeamGoCli.Commands.CommandParameterMetdata;
